/Generator/SingleParticle/particle gamma
/Generator/SingleParticle/min_energy 511 keV
/Generator/SingleParticle/max_energy 511 keV
/Generator/SingleParticle/region OUTSIDE
#/Generator/SingleParticle/min_phi 3.5
#/Generator/SingleParticle/max_phi 5.5

#/Generator/Kr83mGenerator/region OUTSIDE

/Geometry/Cigar/pressure 1.5 bar
/Geometry/Cigar/fiber_diameter 1 mm
/Geometry/Cigar/coating TPB
/Geometry/Cigar/coated true
/Geometry/Cigar/fiber_type Y11
/Geometry/Cigar/gas Xe

/run/verbose 1
/event/verbose 0
/tracking/verbose 0
/process/em/verbose 0

### JOB CONTROL
/nexus/random_seed            27
/nexus/persistency/start_id   0
/nexus/persistency/output_file Cigar
