#/Generator/CORSIKAGenerator/corsika_file /Users/roberto/corsika/DAT000001
#/Generator/CORSIKAGenerator/region DETECTOR
#/Generator/CORSIKAGenerator/plane_y_size 20 m
#/Generator/CORSIKAGenerator/plane_x_size 20 m
#/Generator/CORSIKAGenerator/height 22 m

/Generator/SingleParticle/particle e+
/Generator/SingleParticle/min_energy 30 MeV
/Generator/SingleParticle/max_energy 30 MeV
/Generator/SingleParticle/region DETECTOR
#/Generator/SingleParticle/momentum 0 1 0


#/Generator/BetaDecayGenerator/region DETECTOR
/Geometry/ESSBeam/beam False
/Geometry/ESSBeam/liquido False
/Geometry/ESSBeam/detector_height 4 m
/Geometry/ESSBeam/detector_diam 4 m

/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/em/verbose 0

/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics
/PhysicsList/RegisterPhysics G4HadronElasticPhysicsHP
/PhysicsList/RegisterPhysics G4HadronPhysicsQGSP_BERT_HP
/PhysicsList/RegisterPhysics G4StoppingPhysics
/PhysicsList/RegisterPhysics G4IonPhysics
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics
/PhysicsList/RegisterPhysics G4OpticalPhysics
/process/optical/processActivation Cerenkov true

### JOB CONTROL
/nexus/random_seed            1
/nexus/persistency/start_id   0
/nexus/persistency/outputFile ESSBeam
