/Generator/LambertianGenerator/particle opticalphoton
/Generator/LambertianGenerator/min_energy 3.35 eV # 7.08 for 125 nm, 2.88 for 430 nm, 3.35 for 370 nm
/Generator/LambertianGenerator/max_energy 3.35 eV
/Generator/LambertianGenerator/momentum  0 -1 0
/Generator/LambertianGenerator/min_costheta 0.999999
/Generator/LambertianGenerator/max_costheta 1.
/Generator/LambertianGenerator/region OUTSIDE_FIBER

/Geometry/FiberEfficiency/length 25 cm
/Geometry/FiberEfficiency/fiber_diameter 1 mm
/Geometry/FiberEfficiency/coated false
/Geometry/FiberEfficiency/with_grease false
/Geometry/FiberEfficiency/fiber_type B2
/Geometry/FiberEfficiency/detector_type PMT

/run/verbose 1
/event/verbose 1
/tracking/verbose 1
/process/em/verbose 0

### JOB CONTROL
/nexus/random_seed            -1
/nexus/persistency/start_id   0
/nexus/persistency/outputFile FiberEfficiency.next
