/Generator/SingleParticle/particle opticalphoton
/Generator/SingleParticle/min_energy 3.54 eV
/Generator/SingleParticle/max_energy 3.54 eV
/Generator/SingleParticle/region CENTER

/Geometry/FiberBox/radius 1 cm
/Geometry/FiberBox/length 5 cm
/Geometry/FiberBox/fiber_radius 1 mm

#/run/verbose 1
#/event/verbose 1
#/tracking/verbose 1
/process/em/verbose 0

### JOB CONTROL
/nexus/random_seed            -1
/nexus/persistency/start_id   0
/nexus/persistency/outputFile generic_wls.next