/Generator/SingleParticle/particle opticalphoton
/Generator/SingleParticle/min_energy 7 eV
/Generator/SingleParticle/max_energy 7 eV
/Generator/SingleParticle/region INSIDE_BARREL

/Geometry/FiberBarrel/radius 5.0 mm
/Geometry/FiberBarrel/length 15.0 mm
/Geometry/FiberBarrel/fiber_diameter 1 mm
/Geometry/FiberBarrel/coating TPH
/Geometry/FiberBarrel/fiber_type B2

/run/verbose 1
/event/verbose 0
/tracking/verbose 0
/process/em/verbose 0

### JOB CONTROL
/nexus/random_seed            1
/nexus/persistency/start_id   0
/nexus/persistency/outputFile FiberBarrel.next
