/Generator/SingleParticle/particle gamma
/Generator/SingleParticle/min_energy 511 keV
/Generator/SingleParticle/max_energy 511 keV
/Generator/SingleParticle/region OUTSIDE
/Generator/SingleParticle/momentum 0 0 1
#/Generator/SingleParticle/min_costheta 1
#/Generator/SingleParticle/max_costheta 1
#/Generator/ScintGenerator/nphotons 2500
#/Generator/ScintGenerator/gaussian true
#/Generator/ScintGenerator/fano 2.73

/Geometry/MonolithicCsI/crystal_length 2
/Geometry/MonolithicCsI/crystal_material CsI
/Geometry/MonolithicCsI/back_wrapping true
/Geometry/MonolithicCsI/crystal_width 48 cm

/run/verbose 1
/event/verbose 0
/tracking/verbose 0
/process/em/verbose 0


/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics
/PhysicsList/RegisterPhysics G4HadronElasticPhysicsHP
/PhysicsList/RegisterPhysics G4HadronPhysicsQGSP_BERT_HP
/PhysicsList/RegisterPhysics G4StoppingPhysics
/PhysicsList/RegisterPhysics G4IonPhysics
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics
/PhysicsList/RegisterPhysics G4OpticalPhysics
/process/optical/processActivation Cerenkov true

### JOB CONTROL
/nexus/random_seed            1
/nexus/persistency/start_id   0
/nexus/persistency/output_file MonolithicCsI
