## ----------------------------------------------------------------------------
## nexus | NEXT100.config.mac
##
## Configuration macro to simulate Bi-214 radioactive decays from the
## copper plate of the tracking plane in the NEXT-100 detector.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

##### VERBOSITY #####
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

##### GEOMETRY #####
/Geometry/Next100/elfield false
/Geometry/Next100/max_step_size 1. mm

##### GENERATOR #####
#/Generator/IonGenerator/atomic_number 83
#/Generator/IonGenerator/mass_number 214
/Generator/IonGenerator/atomic_number 54
/Generator/IonGenerator/mass_number 124
/Generator/IonGenerator/region XENON

##### ACTIONS #####
#/Actions/DefaultEventAction/min_energy 0.6 MeV
#/Actions/DefaultEventAction/max_energy 2.55 MeV
/Actions/DefaultEventAction/min_energy 1 keV
/Actions/DefaultEventAction/max_energy 2700 keV

##### PHYSICS #####
## No full simulation
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false

/Actions/DefaultEventAction/enable_clustering true
/Actions/DefaultEventAction/cluster_min_hits 1
/Actions/DefaultEventAction/cluster_radius 100 mm
/Actions/DefaultEventAction/store_max_clusters 3

##### PERSISTENCY #####
/nexus/persistency/output_file Next100_tl208_lighttube.next
## eventType options: bb0nu, bb2nu, background
/nexus/persistency/event_type background
