## ----------------------------------------------------------------------------
## nexus | nexus_NextPrecdr.config.mac
##
## Configuration macro to simulate individual particles
## in a cylindrical xenon volume with copper shell (NextPrecdr).
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

/control/execute macros/geometries/NextPrecdr.mac

/Generator/SingleParticle/particle gamma
/Generator/SingleParticle/min_energy 2614.5 keV
/Generator/SingleParticle/max_energy 2614.5 keV
/Generator/SingleParticle/region COPPER

##### ACTIONS #####
/Actions/DefaultEventAction/min_energy 0.01 keV
/Actions/DefaultEventAction/max_energy 2614.6 keV


/nexus/persistency/output_file tl208_precdr.next
/nexus/persistency/event_type background
