## ----------------------------------------------------------------------------
## nexus | nexus_NextPrecdr.init.mac
##
## Initialization macro to simulate individual particles
## in a cylindrical xenon volume with copper shell (NextPrecdr).
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/control/execute macros/physics/DefaultPhysicsList.mac

/nexus/RegisterGeometry NextPrecdr

#/nexus/RegisterGenerator SingleParticleGenerator
/nexus/RegisterGenerator IonGenerator
#/nexus/RegisterGenerator Decay0Interface
#/nexus/RegisterGenerator ElecPositronPairGenerator

/nexus/RegisterPersistencyManager PersistencyManager

/nexus/RegisterRunAction DefaultRunAction
/nexus/RegisterEventAction DefaultEventAction
/nexus/RegisterTrackingAction DefaultTrackingAction

/nexus/RegisterMacro macros/NextPrecdr.config.mac
/nexus/RegisterDelayedMacro macros/physics/Bi214.mac